version: '3.7'
services:
  racquetball-bot:
    build: .
    container_name: 'racquetball-bot'
    ports:
      - '8080:8080'
    volumes:
      - './app:/go/src/app'
    depends_on:
      - 'mongo'
    environment:
      - PORT=8080
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    ports:
      - 8181:8081